version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/before_script.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_script.sh
      timeout: 300
      runas: root

