version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr-public get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin public.ecr.aws/q1y0j8u6)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t prasad:latest .
      - docker tag prasad:latest public.ecr.aws/q1y0j8u6/prasad:latest    
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/q1y0j8u6/prasad:latest
